= CIDER: An attempt at detailed documentation

The documentation for cider-nrepl is somewhat "whatever cider.el does with
cider-nrepl". This is an attempt to reconcile that with hard information
gleamed whilst writing an nREPL client.

I've attempted to provide reference implementations in Clojure where available,
thinking it the lingua fraca of implementors. This shouldn't be taken to mean
that it's the language you should do this processing in.

== Ops

=== `info`

.Requires
[horizontal]
`ns` key:: the current namespace
`symbol` key:: the symbol to get info on

The return values of this function are hard to parse indepth, it's mostly a pass through of the metadata. Additional keys added:

* `see-also` this was extracted from the clojuredocs database, and is added to info.

==== Implementing a Doc

_Based on the CIDER.el implementation._

NOTE: arglists-str or forms-str will be returned, depending on whether it's a function/macro or a special like `.` or `def`.

There is some work to separate the following:
* Java "things"
* Functions
* Macros
* Vars that don't point to either of the above (Numbers, Strings, etc.)
* Specials

.Determine a human friendly full name for the symbol
[source,clojure]
----
(if (:class message) <1>
  (if (:member message)
    (format "%s/%s" (:class message) (:member message))
    (:member message))
  (if (:ns message)
    (format "%s/%s" (:ns message) (:name message))
    (:name message)))
----
1: The class key is used to check if this is a java symbol, or a clojure one.

=== `refresh` / `refresh-all`

.Parameters
[horizontal]
`before`:: A function to run before refreshing, as a string which will be resolved. The function must take no parameters. (Optional)
`after`:: A function to run after refreshing, as a string which will be resolved. The function must take no parameters. (Optional)
`dirs`:: Used to limit the scope of refreshing. Likely not useful for normal tooling. (Optional)

During the process of generating the below replies, if an exception is thrown (e.g. through your before) then an error-reply will be sent, followed by an empty status done message.

.Replies
* pre-invocation of before (status will be `"invoking-before"`)
[horizontal]
`before`:: The symbol being resolved
`status`:: Constant `"invoking-before"`
* post-invocation of before
[horizontal]
`before`:: The symbol being resolved
`status`:: status will be either `"invoked-before"` or `"invoked-not-resolved"`
* pre-refresh (This contains the list of namespaces to reload)
[horizontal]
`reloading`:: The list of symbols to be reloaded
* post-refresh
** In the case of success
[horizontal]
`status`:: Constant `"ok"`
** In the case of an error
[horizontal]
`error`:: The error (More docs needed on what this error is! I believe something will serialize it later)
`error-ns`:: The namespace which caused the error as a string, e.g. `"clojure.core"`.
* pre-invocation of after
[horizontal]
`after`:: The symbol being resolved
`status`:: Constant `"invoking-after"`
* post-invocation of after
[horizontal]
`after`:: The symbol being resolved
`status`:: status will be either `"invoked-after"` or `"invoked-not-resolved"`
* empty status done message
[horizontal]
`status`:: Constant `"done"`
