= CIDER: An attempt at detailed documentation
:toc:

The documentation for cider-nrepl is somewhat "whatever cider.el does with
cider-nrepl". This is an attempt to reconcile that with hard information
gleamed whilst writing an nREPL client.

I've attempted to provide reference implementations in Clojure where available,
thinking it the lingua fraca of implementors. This shouldn't be taken to mean
that it's the language you should do this processing in.

== Ops

=== `info`

.Requires
[horizontal]
`ns` key:: the current namespace
`symbol` key:: the symbol to get info on

The return values of this function are hard to parse indepth, it's mostly a pass through of the metadata. Additional keys added:

* `see-also` this was extracted from the clojuredocs database, and is added to info.

=== `refresh` / `refresh-all`

.Parameters
[horizontal]
`before`:: A function to run before refreshing, as a string which will be resolved. The function must take no parameters. (Optional)
`after`:: A function to run after refreshing, as a string which will be resolved. The function must take no parameters. (Optional)
`dirs`:: Used to limit the scope of refreshing. Likely not useful for normal tooling. (Optional)

During the process of generating the below replies, if an exception is thrown (e.g. through your before) then an error-reply will be sent, followed by an empty status done message.

.Replies
1. pre-invocation of before (status will be `"invoking-before"`)
[horizontal]
`before`:: The symbol being resolved
`status`:: Constant `"invoking-before"`
2. post-invocation of before
[horizontal]
`before`:: The symbol being resolved
`status`:: status will be either `"invoked-before"` or `"invoked-not-resolved"`
3. pre-refresh (This contains the list of namespaces to reload)
[horizontal]
`reloading`:: The list of symbols to be reloaded
4. post-refresh
** In the case of success
[horizontal]
`status`:: Constant `"ok"`
** In the case of an error
[horizontal]
`error`:: The error (More docs needed on what this error is! I believe something will serialize it later)
`error-ns`:: The namespace which caused the error as a string, e.g. `"clojure.core"`.
5. pre-invocation of after
[horizontal]
`after`:: The symbol being resolved
`status`:: Constant `"invoking-after"`
6. post-invocation of after
[horizontal]
`after`:: The symbol being resolved
`status`:: status will be either `"invoked-after"` or `"invoked-not-resolved"`
7. empty status done message
[horizontal]
`status`:: Constant `"done"`

=== `apropos`: Search for vars

[quote,cider-nrepl source]
____
This middleware provides regular expression search across namespaces for both symbols and documentation.
Results ordered for the most common usages:
symbols from the current namespace are preferred, then `clojure.*` symbols, and then other results.
____

.Parameters
[horizontal]
`ns`:: Priority namespace to list.
This is intended to be current namespace.
The matches will list this namespace first.
`query`:: Regexp to match symbols against
`search-ns`:: This will be the only namespace searched if provided
`docs?`:: Predicate, whether or not to search docstrings
`privates?`:: Whether or not to include private symbols
`case-sensitive?`:: Case sensitivity of the regexp
`filter-regexps`:: Remove symbols which match this regexp

You receive a single reply, containing the list of matches under the key `apropos-matches`.

.Apropos Matches
[horizontal]
`name`:: Full name of the matched symbol
`doc`:: Docstring of the matched symbol
`type`:: One of `"special-form"`, `"macro"`, `"function"` or `"variable"`

=== `classpath`

Get a list of the classpath.
Uses clojure.java.classpath under the hood.

.Parameters
None

.Response
[horizontal]
`classpath`:: A list of strings which is the classpath

=== Test middleware

.List of test-related ops
* `test`
* `test-all`
* `test-stacktrace`
* `retest`

`test` and `test-all` are very similar, except in scope.
They run tests, and produce a test report.

.`test` parameters
[horizontal]
`ns`:: Namespace to run tests for.
`tests`::
A list of vars to test.
If not supplied, then all tests for the current `ns` will be run.
If supplied, should be a list of strings, which will be resolved within the `ns` parameter.
`selector`:: Filter vars to only those where `(keyword "selector")` resolves to true in the metadata. e.g. if the var was defined with `^:foobar` then a selector of `"foobar"` would run this test.

.`test-all` parameters
[horizontal]
`load?`:: Set to any value (I prefer `1`) if this should load namespaces (`require` them) or just use the already loaded ones.
`selector`:: Filter vars to only those where `(keyword "selector")` resolves to true in the metadata. e.g. if the var was defined with `^:foobar` then a selector of `"foobar"` would run this test.

`retest` re-runs all the tests that failed in the last run of `test` or `test-all`.
It takes no parameters.
It returns a test report also.

.Test report format
____
A map containg the keys:

[horizontal]
`summary`:: A summary of pass/failures, with a breakdown by category
`results`:: A <<results-map>> describing failures in details
`testing-ns`:: ???
`gen-input`:: ???

[[results-map]]
_____
A map of namespace to map of vars.
The map of vars is a list of maps.
The list of maps contains information about the success/failures inside of that test.


.Basic form
----
{'my-api'
 {'my-var': []}}
----

WARNING: I have not yet documented the assertions.

_____

____

`test-stacktrace` is a useful op for using CIDER's stacktrace functionality to inspect a stacktrace that happens during a test.

.`test-stacktrace` parameters
[horizontal]
`ns`:: Namespace of test that failed.
`var`:: Var within that namespace that failed.
`index`:: Index of test that failed

See <<stacktrace>> for more info.

[[stacktrace]]
=== `stacktrace` middleware


